services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=America/Bogota
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/edwardarroyave/RESPOSITORIOS:/home/jenkins/RESPOSITORIOS
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - CI-CD

networks:
  CI-CD:
    driver: bridge

volumes:
  jenkins_data:
