version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/edwardarroyave/RESPOSITORIOS:/home/jenkins/RESPOSITORIOS
    networks:
      - CI-CD

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/prometheus
    networks:
      - CI-CD
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - CI-CD
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  jenkins_data:
  prometheus_data:
  sonarqube_data:

networks:
  CI-CD:
    driver: bridge
