version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=America/Bogota
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/edwardarroyave/RESPOSITORIOS:/home/jenkins/RESPOSITORIOS
    networks:
      - CI-CD

networks:
  CI-CD:
    driver: bridge
