services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=America/Bogota
    volumes:
      - ci-cd_jenkins_data:/var/jenkins_home
    user: root
    networks:
      - CI-CD

  postgres:
    image: postgres:15
    container_name: sonarqube_postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      TZ: America/Bogota
    volumes:
      - ci-cd_postgres_data:/var/lib/postgresql/data
    networks:
      - CI-CD

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - ci-cd_sonarqube_data:/opt/sonarqube/data
      - ci-cd_sonarqube_extensions:/opt/sonarqube/extensions
      - ci-cd_sonarqube_logs:/opt/sonarqube/logs
    networks:
      - CI-CD

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/edwardarroyave/CI-CD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ci-cd_prometheus_data:/prometheus
    networks:
      - CI-CD

networks:
  CI-CD:
    driver: bridge

volumes:
  ci-cd_jenkins_data:
    external: true

  ci-cd_postgres_data:
    external: true

  ci-cd_sonarqube_data:
    external: true

  ci-cd_sonarqube_extensions:
    external: true

  ci-cd_sonarqube_logs:
    external: true

  ci-cd_prometheus_data:
    external: true